Imports System.ComponentModel
Imports System.Drawing
Imports System.Windows.Forms

Namespace WinPivot_GettingStarted

    Public Partial Class Form1
        Inherits Form

        Public Sub New()
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            ' Fill the SqlDataSource
            sqlDataSource1.Fill()
            pivotGridField5.Options.HideEmptyVariationItems = True
            pivotGridControl1.BestFit()
        End Sub
    End Class
End Namespace
