Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Linq
Imports System.Text
Imports System.Threading.Tasks
Imports System.Windows.Forms

Namespace WinPivot_GettingStarted
	Partial Public Class Form1
		Inherits Form

		Public Sub New()
			InitializeComponent()
			' This line of code is generated by Data Source Configuration Wizard
			' Fill the SqlDataSource
			sqlDataSource1.Fill()
			pivotGridField5.Options.HideEmptyVariationItems = True
			pivotGridControl1.BestFit()
		End Sub
	End Class
End Namespace
